name: Flutter CI
on:
  push:
    paths: ["mobile-app/student-app/**"]
  pull_request:
    paths: ["mobile-app/student-app/**"]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile-app/student-app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
